version: '3.0'

services:
  db:
    image: 'postgres'
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=vacationDB
#  admin-service:
#    image: 'admin'
#    container_name: admin-service
#    build: ./
#    depends_on:
#      - db
#    ports:
#      - "8080:8080"
#  search-service:
#    image: 'search'
#    container_name: search-service
#    build: ../search
#    depends_on:
#      - db
#    ports:
#        - "8081:8081"